image: openjdk:11-jdk

stages:
    - build
    - run

before_script:
    #  - echo `pwd` # debug
    #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

build:
    stage: build
    script:
        - ./gradlew clean build jacocoTestReport
        - "cat build/jacocoHtml/index.html"

run:
    stage: run
    script:
        - ./gradlew run

after_script:
    - echo "End CI"
